/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./src/components/tabs/AboutTab.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    RecipeTab: typeof import('./src/components/tabs/RecipeTab.vue')['default']
    SearchQueriesTab: typeof import('./src/components/tabs/SearchQueriesTab.vue')['default']
    SettingsTab: typeof import('./src/components/tabs/SettingsTab.vue')['default']
  }
}
