/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '(копия)': typeof import('./src/components/ingredients/IngredientListItem (копия).vue')['default']
    AboutTab: typeof import('./src/components/tabs/AboutTab.vue')['default']
    AutocompleteField: typeof import('./src/components/common/AutocompleteField.vue')['default']
    FieldAutocomplete: typeof import('./src/components/common/FieldAutocomplete.vue')['default']
    FieldNumber: typeof import('./src/components/common/FieldNumber.vue')['default']
    FieldWithFilter: typeof import('./src/components/common/FieldWithFilter.vue')['default']
    FileInput: typeof import('./src/components/common/FileInput.vue')['default']
    FileOutput: typeof import('./src/components/common/FileOutput.vue')['default']
    HashtagListEditor: typeof import('./src/components/hashTags/HashtagListEditor.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    IngredientDataInput: typeof import('./src/components/ingredients/IngredientDataInput.vue')['default']
    IngredientList: typeof import('./src/components/ingredients/IngredientList.vue')['default']
    IngredientListEditor: typeof import('./src/components/ingredients/IngredientListEditor.vue')['default']
    IngredientListHeader: typeof import('./src/components/ingredients/IngredientListHeader.vue')['default']
    IngredientListItem: typeof import('./src/components/ingredients/IngredientListItem.vue')['default']
    QuantityField: typeof import('./src/components/common/QuantityField.vue')['default']
    Recipe: typeof import('./src/components/Recipe.vue')['default']
    RecipesSearchItem: typeof import('./src/components/search/RecipesSearchItem.vue')['default']
    RecipeTab: typeof import('./src/components/tabs/RecipeTab.vue')['default']
    SearchTab: typeof import('./src/components/tabs/SearchTab.vue')['default']
    SettingsTab: typeof import('./src/components/tabs/SettingsTab.vue')['default']
    SimpleButton: typeof import('./src/components/common/SimpleButton.vue')['default']
    SimpleCheckbox: typeof import('./src/components/common/SimpleCheckbox.vue')['default']
  }
}
